In [1]:
import numpy as np

In [23]:
my_lst1=[1,2,3,5,6]
my_lst2=[2,3,4,5,6]
my_lst3=[4,5,6,7,8]

In [24]:
arr=np.array([my_lst1,my_lst2,my_lst3])

In [25]:
type(my_lst)

list

In [26]:
type(arr)

numpy.ndarray

In [27]:
arr

array([[1, 2, 3, 5, 6],
       [2, 3, 4, 5, 6],
       [4, 5, 6, 7, 8]])

In [28]:
arr.shape

(3, 5)

In [29]:
arr

array([[1, 2, 3, 5, 6],
       [2, 3, 4, 5, 6],
       [4, 5, 6, 7, 8]])

In [31]:
arr.reshape(5,3)

array([[1, 2, 3],
       [5, 6, 2],
       [3, 4, 5],
       [6, 4, 5],
       [6, 7, 8]])

In [34]:
arr[0:2,0:2]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [35]:
my_lst1=[1,2,3,5,6]
my_lst2=[2,3,4,5,6]
my_lst3=[4,5,6,7,8]


In [4]:
arr=np.array([my_lst1,my_lst2,my_lst3])

NameError: name 'np' is not defined

In [37]:
arr

array([[1, 2, 3, 5, 6],
       [2, 3, 4, 5, 6],
       [4, 5, 6, 7, 8]])

In [38]:
arr[0:2,0:2]

array([[1, 2],
       [2, 3]])

In [39]:
arr[0:3,0:2]

array([[1, 2],
       [2, 3],
       [4, 5]])

In [40]:
arr[0:1,0:3]

array([[1, 2, 3]])

In [41]:
arr[1:,3:]

array([[5, 6],
       [7, 8]])

In [42]:
arr[2:,4:]

array([[8]])

In [44]:
arr[1:2,1:4]

array([[3, 4, 5]])

In [46]:
arr[1:2,2:5]

array([[4, 5, 6]])

In [2]:
arr[0:2,4:5]

NameError: name 'arr' is not defined

NameError: name 'arr' is not defined

In [5]:
my_list1={1,2,3,4,5,6}
my_list2={2,3,4,5,6,7}
my_list3={3,4,5,6,7,8}

In [6]:
arr=np.array([my_list1,my_list2,my_list3])

NameError: name 'np' is not defined